### ISSUE TITLE
GraphQl Magento 2.4.3-p1 issue with ideal issuer_id

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2#33] opened 2022-05-20 14:05 UTC
**Describe the bug**
When you set a ideal issuer_id and then place order the issuer_id gets removed. The reason for this is that Magento has decided to change the logic for the GraphQl endpoint to always include the payment data and this resets the additional_data which removes the issuer_id. 

**To Reproduce**
1. Create a cart with an item.
2. Set Ideal payment method with an issuer_id through graphql
3. Place order through graphql without setting the payment method again.

**Expected behavior**
You get a link to the issuers page to handle the payment there.

**Actual behavior**
You get a link to MSP where you have to select an issuer.

**Additional context**
Cause of the issue is the `$this->cartManagement->placeOrder($cartId, $this->paymentMethodManagement->get($cartId));` line in the `Magento/QuoteGraphQl/Model/Resolver/PlaceOrder` class. In older versions the `$this->paymentMethodManagement->get($cartId)` doesn't exist.

**Comment by danielcivit** [comment] 2022-05-24 07:08
Hi @Hexmage 

Thanks for this report.  
We will be investigating this issue and will get back to you as soon as possible with our findings.

**Comment by vinodsowdagar** [comment] 2022-06-29 15:45
Hi @Hexmage ,

We have released a new version of our module where the fix is implemented:
https://github.com/MultiSafepay/magento2/releases/tag/2.18.0

The issue should not be happening anymore after an upgrade. 
If you still experience issues or have other questions, feel free to create a new issue or reopen this one.

**Comment by Hexmage** [comment] 2022-06-30 09:39
@Vinod-MultiSafepay 
Similar things are happening to other payment methods. When you try to set specific data for Klarna, this gets deleted as well in the same way.

**Comment by vinodsowdagar** [comment] 2022-06-30 14:35
Hi @Hexmage ,

We don't expect someone to set additional information for a payment method where it is not needed to create the transaction. Perhaps this is why the issue is happening.

Can you show us an example of GraphQL requests with the payload that you are using where you are experiencing issues with?

I reopened this one in the meantime.

**Comment by danielcivit** [comment] 2023-01-26 13:03
We are closing this ticket due inactivity.

**Closed as completed by danielcivit** 2023-01-26 13:03 UTC
