### ISSUE TITLE
Custom fee not being added to the final totals

### ISSUE THREAD

**Issue by SinpietruAdrian** [MultiSafepay/magento2#6] opened 2021-01-28 11:38 UTC
The total on the Multisafepay page is incorrect because it does not take into account the additional fees introduced by the 3rd party module even if on the website the totals are calculated and displayed correctly.

In cart:
<img width="340" alt="Screenshot 2021-01-27 at 12 50 07" src="https://user-images.githubusercontent.com/28003438/106133332-c5a22700-616d-11eb-9d34-20be1b43af68.png">

The totals segments:
<img width="401" alt="Screenshot 2021-01-27 at 12 50 48" src="https://user-images.githubusercontent.com/28003438/106133361-d2267f80-616d-11eb-97d7-9f922eba307c.png">

The total as seen on the Multisafepay page:
<img width="882" alt="Screenshot 2021-01-27 at 12 51 33" src="https://user-images.githubusercontent.com/28003438/106133388-dc487e00-616d-11eb-970a-b8ef935f628c.png">

Using multisafepay/magento2: 2.3.0 and prince/magento2-extrafeepro 1.0.7.
This was reproduced on a clean Magento 2.3.2 and on a Magento 2.3.6 that contains multiple modules.

Thank you!

**Comment by vinodsowdagar** [comment] 2021-02-01 14:24
Hi @SinpietruAdrian ,

Thank you for your report. 
This feature should be working as we have confirmed it to work with other modules as well.
We have sent an e-mail to Mageprince regarding this issue and we are waiting for a reply, so we can investigate this further.

If you have any questions in the meantime, please let us know.

**Comment by vinodsowdagar** [comment] 2021-03-17 15:23
Hi @SinpietruAdrian ,

We released a fix for this issue recently: 
https://github.com/MultiSafepay/magento2/releases/tag/2.5.0

For now i am closing this issue, since it should already be resolved by updating to the latest version.
Feel free to create a new issue or re-open this one if you still have questions regarding this matter.

**Closed as completed by vinodsowdagar** 2021-03-17 15:23 UTC
