### ISSUE TITLE
Error while compilation magento 2 update

### ISSUE THREAD

**Issue by godrigon** [MultiSafepay/magento2#63] opened 2024-03-25 09:28 UTC
we are facing this issue while we are updating our portal from 2.3.4. to 2.4.6.

Compilation was started. Area configuration aggregation... 5/9 [===============>------------] 55% 30 secs 370.0 MiB In ClassReader.php line 57:

Impossible to process constructor argument Parameter #21 [ Magento\InventoryApi\Api\GetSourceItemsBySkuInterface $sourceItemsBySku ] of Mageplaza\Seo\Plugin\SeoRender class

In GetParameterClassTrait.php line 34:

Class "Magento\InventoryApi\Api\GetSourceItemsBySkuInterface" does not exist

setup:di:compile

Do you have any idea how to solve this problem? We are updating all plugins and the magento is already on 2.4.6. p4

**Comment by danielcivit** [comment] 2024-03-25 12:05
Hello @godrigon 

It seems to us the problem is related to a Mageplaza module.  Following the error message:

Impossible to process constructor argument Parameter https://github.com/MultiSafepay/magento2/issues/21 [ Magento\InventoryApi\Api\GetSourceItemsBySkuInterface $sourceItemsBySku ] of **Mageplaza\Seo\Plugin\SeoRender** class

I recommend contacting Mageplaza support and asking about their module and support for the latest version of Magento.

For the moment; I will close this ticket, but if you think this issue is related to the MultiSafepay module, please feel free to reopen it; or create another one.

**Closed as completed by danielcivit** 2024-03-25 12:05 UTC

**Comment by godrigon** [comment] 2024-03-25 12:26
Thank you, but the problem is that our Magento 2.4.6. does not have this Magento/InventoryApi directory at all. 

What should we do with that?
